/* TRex Profile & Config Builder - help copy: the single source of truth for
 * field tooltips AND the Manual tab's auto-generated field-reference tables.
 * Structure per tab: _tab (one-line purpose), _sections (per collapsible
 * section), then one entry per field. Keep entries short, concrete and
 * TRex-accurate - they appear verbatim in tooltips. */
(function (root) {
  'use strict';
  var TB = root.TB = root.TB || {};

  TB.help = {
    stl: {
      _tab: 'Builds stateless (STL) traffic profiles: Python files defining packet streams that TRex transmits at a set rate, with optional per-packet field mutation.',
      _sections: {
        packet: 'What each transmitted packet looks like: L2/VLAN/L3/L4 headers plus padding to the target frame size.',
        mode: 'How the stream transmits: continuously, one burst, or repeated bursts.',
        chain: 'When the stream starts and what it triggers next - used to sequence streams.',
        vm: 'The TRex Field Engine: mutates packet fields per packet (IP sweeps, random ports, tuple pools) so traffic is not identical.',
        flowStats: 'Per-stream counters or latency measurement, identified by a packet-group id (pg_id).',
        tunables: 'Named parameters exposed as --args of get_streams(); change values at load time without editing the profile.',
        pcapReplay: 'Replay a capture file as stateless streams via STLProfile.load_pcap (like the shipped stl/pcap.py). While enabled, the stream list and tunables are ignored.'
      },
      pcapReplayOn: 'Generate a load_pcap profile instead of building streams: TRex replays every packet of the capture.',
      pcapReplayFile: 'Pcap path relative to the TRex directory (e.g. cap2/dns.pcap). With the Flask backend running, Browse… lists real files.',
      pcapReplayIpg: 'Microseconds between replayed packets. Leave empty to keep the timing recorded in the pcap.',
      pcapReplaySpeedup: 'Divides the pcap inter-packet gaps: 2 replays twice as fast. Only applies when IPG is empty (pcap timing).',
      pcapReplayLoop: 'How many times to replay the capture; 0 loops forever.',
      profileName: 'Name used for the generated .py file and when saving/loading this profile in the app.',
      trexVersion: 'TRex version the generated code targets. Only v3.06 generators are registered today.',
      streamName: 'Python-side stream name; other streams reference it in "next" chains.',
      srcMac: 'Override the Ethernet source MAC. Leave empty to let TRex use the port MAC from trex_cfg.yaml.',
      dstMac: 'Override the Ethernet destination MAC. Leave empty to use the resolved gateway/dest MAC.',
      vlan: 'Insert an 802.1Q VLAN tag between Ethernet and L3.',
      vlanId: 'VLAN identifier (1-4094).',
      vlanPrio: '802.1p priority bits (0-7).',
      tunnel: 'Wrap the packet in an encapsulation: VXLAN or GRE (outer IP tunnel), MPLS label, QinQ 802.1ad outer VLAN, or an NSH service header. The L3/L4 form below becomes the INNER packet.',
      tunnelOuterSrc: 'Outer tunnel IPv4 source (the tunnel endpoint sending the traffic).',
      tunnelOuterDst: 'Outer tunnel IPv4 destination (the far tunnel endpoint).',
      vni: 'VXLAN network identifier (24-bit). Outer UDP uses the standard port 4789.',
      mplsLabel: 'MPLS label value (20-bit).',
      mplsTtl: 'MPLS TTL (optional; scapy default when empty).',
      qinqOuter: '802.1ad (Dot1AD) outer service VLAN. Tick the VLAN checkbox above to add the inner 802.1Q customer tag.',
      nshSpi: 'NSH service path identifier.',
      nshSi: 'NSH service index (hops remaining on the path).',
      l3: 'Network layer: IPv4 or IPv6.',
      srcIp: 'Source IP written into every packet (the Field Engine can then sweep/randomise it).',
      dstIp: 'Destination IP written into every packet.',
      tos: 'IPv4 TOS/DSCP byte (optional).',
      ttl: 'IPv4 time-to-live (optional).',
      l4: 'Transport layer: UDP, TCP, ICMP echo, or none (bare L3).',
      sport: 'Source port.',
      dport: 'Destination port.',
      tcpFlags: 'TCP flags string, e.g. "S" for SYN - used for SYN-flood style streams.',
      icmpKind: 'Echo request (ping) or echo reply. Uses ICMP on IPv4 and ICMPv6 on IPv6.',
      icmpId: 'ICMP echo identifier (optional). Replies must echo the request id.',
      icmpSeq: 'ICMP echo sequence number (optional).',
      fragOffset: 'IPv4 fragment offset in 8-byte units (optional) - non-zero marks this packet as a later fragment.',
      moreFrags: 'Sets the IPv4 More-Fragments flag: this packet is a fragment with more to follow.',
      ipv6Ext: 'Insert an IPv6 extension header between IPv6 and L4: hop-by-hop options or a fragment header.',
      packetPresets: 'One-click packet templates. ICMP echo fills the form; ARP request and DNS query need layers the form does not model, so they fill the raw scapy field (frame-size padding does not apply).',
      frameSize: 'Total on-wire frame size in bytes including headers; the payload is padded to reach it. Below 60 B many NICs pad or reject frames.',
      bindTunable: 'Bind this field to a tunable so its value comes from --<name> at load time instead of a literal.',
      fill: 'Character used to pad the payload.',
      rawScapy: 'Escape hatch: a raw scapy expression that replaces the whole packet definition. Emitted verbatim and NOT validated by the app.',
      mode: 'continuous = fixed pps until stopped; single burst = N packets then stop; multi burst = repeated bursts with a gap.',
      pps: 'Transmit rate at -m 1, in the selected unit. The console -m multiplier scales all streams proportionally at run time.',
      rateUnit: 'Rate unit: pps (packets/s), bps L1 (bits/s incl. preamble + inter-frame gap), bps L2 (bits/s of the Ethernet frame), or percentage of the port line rate.',
      totalPkts: 'Number of packets in the single burst.',
      pktsPerBurst: 'Packets in each burst.',
      ibg: 'Inter-burst gap in microseconds between bursts.',
      count: 'Number of bursts to send.',
      isg: 'Inter-stream gap: delay in microseconds before this stream starts. Staggered isg values create rate ramps.',
      selfStart: 'Ticked: stream starts on its own. Unticked: it only runs when another stream triggers it via "next".',
      next: 'Stream to trigger when this one finishes its burst - chains streams into sequences or loops.',
      actionCount: 'With a "next" loop back to an earlier stream: how many times to loop (0 = forever).',
      vmVarName: 'Field Engine variable name (referenced by the write instruction).',
      vmSize: 'Variable width in bytes: 1, 2, 4 or 8 - must cover the packet field it writes to.',
      vmOp: 'How the value changes per packet: inc, dec, or random within min-max.',
      vmMin: 'Lowest value (IPs allowed for 4-byte vars).',
      vmMax: 'Highest value.',
      vmStep: 'Increment step (default 1).',
      vmWriteTo: 'Packet field the variable overwrites, e.g. IP.src, UDP.sport, or a raw byte offset.',
      vmNextVar: 'Nested-loop dependency: when THIS variable wraps past its max, the selected variable advances one step (dependent_field_engine_vars.py pattern).',
      vmOffsetFixup: 'Bytes added to the write offset - lets a small variable land in the tail of a wider field (e.g. 2-byte var into the low half of an IP address).',
      vmSplitCores: 'Ticked: each TX core gets its own slice of the value range (default). Untick so every core sweeps the FULL range (split_var_to_cores.py pattern).',
      vmFixCsum: 'Recalculate the IPv4 checksum after the write (needed whenever IP header bytes change).',
      tuple: 'Tuple generator: produces unique (client IP, port) pairs - the standard way to emulate many clients.',
      tupleLimit: 'Maximum number of distinct flows the tuple pool generates.',
      cacheSize: 'Pre-compute this many mutated packets and replay them - big CPU saving for repetitive mutation.',
      fsType: 'none | flow stats (tx/rx counters per pg_id) | latency (adds latency/jitter measurement).',
      pgId: 'Packet-group id identifying this stream in flow-stat reports. Each LATENCY stream needs a unique pg_id.',
      addPortId: 'Adds the port number to pg_id so the same profile stays unique when loaded on several ports.',
      tunableName: 'Argument name: becomes --<name> when loading the profile.',
      tunableType: 'Argument type used by argparse (int/float/str/choice).',
      tunableDefault: 'Value used when the argument is not given.',
      tunableHelp: 'Help text shown by --help.'
    },

    astf: {
      _tab: 'Builds advanced stateful (ASTF) profiles: full TCP/UDP connections between emulated clients and servers, from replayed pcaps or scripted send/recv programs.',
      _sections: {
        ipGen: 'The client and server IP pools TRex allocates connections from. Ranges must be routable through the device under test.',
        globals: 'Optional per-side (client/server) tuning: TCP stack parameters, IPv6, and the CPS ramp-up scheduler.',
        cap: 'One replayed pcap: TRex re-plays the captured flow, rewriting IPs from the generator pools.',
        template: 'One traffic template: a client program and a server program tied together on an association port.',
        presets: 'Ready-made profiles: DNS/SIP/RTP UDP programs, HTTPS via TLS pcap, an SFR-style multi-pcap enterprise mix, and an elephant-flow throughput soak (http_eflow.py pattern). Loading one replaces the current entries; everything stays editable afterwards.',
        tunnelsTopo: 'Mobile-network testing (astf/gtpu_topo.py): wraps each client\'s traffic in a GTP-U tunnel with its own TEID. Generates a companion _topo.py file loaded in the console with "tunnels_topo load" before starting the profile.'
      },
      topoOn: 'Adds a second generated file defining TunnelsTopo contexts. Client-side packets are GTP-U encapsulated per the contexts below; the profile itself is unchanged.',
      topoSrcRange: 'The slice of the CLIENT pool this tunnel context covers (always IPv4). Each client in the slice gets its own TEID.',
      topoTeid: 'TEID assigned to the first client in the range.',
      topoTeidJump: 'TEID increment between consecutive clients.',
      topoSport: 'Outer UDP source port of the GTP-U encapsulation (destination is the standard 2152).',
      topoVersion: 'IP version of the OUTER tunnel packet. The inner client addresses stay IPv4.',
      topoSrcIp: 'Outer tunnel source endpoint (e.g. the simulated eNodeB/gNB address).',
      topoDstIp: 'Outer tunnel destination endpoint (e.g. the UPF/SGW under test).',
      topoActivate: 'Untick to define the context without activating it at load time (activate later from the API).',
      profileName: 'Name used for the generated .py file and when saving/loading in the app.',
      mode: 'pcap list: replay captured flows (easiest, realistic). program: script the exchange yourself with send/recv commands.',
      clientRange: 'Client-side IP pool; TRex sources connections from these addresses.',
      serverRange: 'Server-side IP pool; TRex answers on these addresses.',
      distribution: 'seq allocates addresses in order; rand picks randomly from the range.',
      perCore: 'Per-core distribution: seq gives each TRex core a contiguous slice of the range (useful for RSS/dual-port setups).',
      ipOffset: 'Offset added to both pools per extra port pair, keeping dual-port traffic in separate subnets.',
      pcapFile: 'Path to the pcap ON THE TREX BOX, relative to the profile (e.g. ../avl/x.pcap).',
      cps: 'Connections per second this entry contributes at -m 1. Relative cps values set the traffic mix; -m scales everything at run time.',
      portPin: 'Force this template onto a specific destination port instead of the one detected from the pcap.',
      sDelay: 'Extra server-side response delay in microseconds.',
      ipGenOverride: 'Give this entry its own client/server IP pools instead of the profile default.',
      tgName: 'Template-group name: groups stats for related templates in the console.',
      assocPort: 'Destination port the server side listens on; the client connects to it. Must be unique per template.',
      transport: 'TCP exchanges a byte stream (send/recv); UDP exchanges datagrams (send_msg/recv_msg).',
      cmdSend: 'Queue a payload to the peer. HTTP presets generate realistic request/response bytes.',
      cmdRecv: 'Block until N bytes arrive. "auto" matches the peer’s send so the sizes never drift.',
      cmdDelay: 'Pause the program - emulates think time or server processing.',
      cmdLoop: 'set_var/set_label/jmp_nz form counted loops, e.g. a server that sends its response 10 times.',
      httpBodyBytes: 'Body size of the generated HTTP response; Content-Length is set to match.',
      tcpTuning: 'Only non-empty fields are emitted. mss/buffers/initwnd shape throughput; keepalive fields hold long idle flows.',
      rampupSec: 'Linear CPS ramp: reach the full connection rate after N seconds. Client side drives the ramp.',
      ipv6: 'Wrap the (IPv4-derived) addresses in IPv6 using the given src/dst most-significant bytes.'
    },

    cap2: {
      _tab: 'Builds legacy stateful (STF) YAML profiles: the classic cap2 format that replays pcap templates with IP rewriting, run via t-rex-64 -f <profile>.yaml.',
      _sections: {
        generator: 'The IP tuple pool: client/server ranges the replayed flows are rewritten to use.',
        flags: 'Global replay behaviour: packet timing, VLAN load-balancing, MAC derivation.',
        cap: 'One pcap template with its own rate, timing and optional payload-rewrite rules.'
      },
      profileName: 'Name for the generated .yaml file and app save slot.',
      duration: 'Test length in seconds (t-rex-64 -d can extend/override at run time).',
      clientsRange: 'Client IP pool flows are sourced from.',
      serversRange: 'Server IP pool flows are destined to. Must not overlap the client range.',
      clientsPerGb: 'Scales how many client addresses are used per Gb/s of traffic.',
      minClients: 'Lower bound on the number of active client addresses.',
      dualPortMask: 'IP offset added on the second port pair so each pair uses its own subnet.',
      aging: 'Seconds before an idle flow entry is recycled (0 = default).',
      capIpg: "Replay packets with the pcap's own recorded inter-packet gaps instead of the fixed ipg below.",
      capOverrideIpg: 'Force every template to this inter-packet gap (microseconds).',
      capIpgMin: 'Lower bound applied to pcap-derived gaps.',
      vlanLb: 'Alternate flows between two VLAN tags - the classic load-balancing trick.',
      macOverrideByIp: 'Derive packet MACs from the IPs instead of the port config.',
      pcapName: 'Pcap path relative to the TRex directory (e.g. cap2/dns.pcap or avl/....pcap).',
      cps: 'Flows started per second from this template (absolute; the mix weight across templates).',
      ipg: 'Inter-packet gap within a flow, microseconds.',
      rtt: 'Assumed round-trip time, microseconds - shapes request/response spacing.',
      w: 'Scheduler weight (leave 1 unless tuning burstiness).',
      limit: 'Cap on simultaneously active flows from this template.',
      pluginId: 'Protocol helper: 4 = HTTP, 5 = DHCP - enables protocol-aware replay.',
      dynPktId: 'Which packet of the pcap (1-based) gets its payload rewritten.',
      dynOffset: 'Byte offset into that packet’s payload where rewriting starts.',
      dynType: '0 writes random data; 1 writes the flow’s client IP - makes each replayed flow unique.',
      dynLen: 'How many 32-bit words to rewrite.',
      dynMask: 'Bitmask applied to the written words (0xffffffff = replace fully).'
    },

    scenarios: {
      _tab: 'Guided wizards for common test setups: a connectivity pre-check, a two-box send/receive run (one-way or bidirectional), an N-stage connection ramp, and an automated NDR benchmark. Each generates a step-by-step RUNBOOK (plus a ready profile where one is needed).',
      _sections: {
        connCheck: 'Prove the network path works before generating any load: service-mode ARP + ICMP ping from the console (no profile needed), plus an optional near-zero-rate latency probe stream that shows average/jitter/max through the DUT.',
        twoServer: 'One TRex box plays the traffic client, a second box plays the server; both load the SAME profile with different CLI flags. Tick "Bidirectional" for both boxes to run client AND server roles simultaneously.',
        ramp: 'Grow the offered load through any number of increasing stages using the mechanism that best fits your test.',
        ndr: 'Drives the shipped ./ndr tool: it binary-searches for the No-Drop Rate against a running interactive TRex instance - no manual -m stepping. STL finds a % of line rate; ASTF finds a -m multiplier between your low/high bounds.'
      },
      rampStages: 'Any number of stage rates, comma-separated and strictly increasing, e.g. "100, 500, 1000, 2000". Each stage runs for the stage duration.',
      bidirectional: 'Both boxes launch with --astf-client-mask 0x1 and both start the profile: each box initiates connections from its port 0 while serving on the other port, so traffic flows in both directions simultaneously.',
      ndrEngine: 'STL searches transmit rate as % of line rate (needs --ports). ASTF searches the -m multiplier between explicit low/high bounds (the shipped tool has no defaults for them).',
      ndrRate: 'For a generated profile this sets the traffic shape (STL stream pps / ASTF cps at -m 1); the benchmark scales it during the search.',
      ndrPorts: 'Even list of port ids the benchmark transmits on, e.g. "0 1" (pairs).',
      ndrPdr: 'Allowed drop percentage. 0 = strict No-Drop Rate; e.g. 0.1 = 0.1% drops tolerated (PDR).',
      ndrMults: 'ASTF search bounds: the tool binary-searches -m between low and high. NDR cps = profile cps x found multiplier.',
      ndrQfull: 'Percent of traffic allowed to sit queued in TX before the rate counts as beyond DUT capability. 0 is not recommended (precision).',
      ndrLatGate: 'Optional latency gate: a rate also fails if latency exceeds max-latency (usec) for more than lat-tolerance % of probes (0% = compare against the max seen).',
      pingDst: 'IPv4 address this port pings - use an address on the FAR side so the reply proves routing through the DUT, not just the local gateway.',
      latencyProbe: 'Also generate a tiny STL profile: one 64-byte UDP latency stream (STLFlowLatencyStats) at a near-zero rate. The tui latency window then shows average/jitter/max and drop counts through the DUT.',
      probePps: 'Probe rate. Keep it low (default 100 pps = ~50 kbit/s) - this validates the path, it is not a load test. Latency streams ignore the -m multiplier.',
      mechanismTwoServer: 'ASTF split (recommended): full TCP connections between the boxes. STL unidirectional: raw packets one way, counters on the receiver.',
      senderHost: 'Label for the client-side box used in the runbook text.',
      receiverHost: 'Label for the server-side box used in the runbook text.',
      rampMechanism: '-m stepping = exact plateaus via console restarts; rampup_sec = smooth linear growth; weighted mix = steady blend at the high rate (approximation).',
      stageRates: 'The three target rates. Must strictly increase: low < mid < high.',
      stageSec: 'How long each stage lasts.'
    },

    cfg: {
      _tab: 'Generates trex_cfg.yaml - the platform file telling TRex which NICs to own (PCI), how many cores to use, and each port’s L2/L3 identity. Installed as /etc/trex_cfg.yaml on the box.',
      _sections: {},
      server: 'Which server (from Settings) to generate the config for.'
    },

    cli: {
      _tab: 'Composes the t-rex-64 launch command (and the matching trex-console session for interactive modes) with valid flags for the chosen mode.',
      _sections: {},
      server: 'Prefills cores and the TRex directory from the Settings registry.',
      mode: 'Interactive modes start a server you drive from trex-console; legacy STF runs a cap2 YAML profile directly to completion.',
      profile: 'Profile the console will start (interactive) or t-rex-64 -f will run (legacy).',
      cfgPath: 'Platform config passed with --cfg; defaults to /etc/trex_cfg.yaml when omitted.',
      cores: 'Data-plane cores per dual-interface (-c).',
      mult: 'Rate multiplier (-m): scales every stream/template proportionally.',
      duration: 'Run length in seconds (-d).',
      latency: 'Latency probe rate in pps (-l) - legacy/ASTF only; STL latency comes from latency streams in the profile.',
      flowAffinity: '-p: send all of a flow’s packets from one port (legacy mode).',
      serverOnly: 'This box only answers connections (the receiver in a two-box setup). Generates no load.',
      clientMask: 'Hex bitmask of local ports that act as the traffic client, e.g. 0x1 = port 0 only.',
      extraArgs: 'Appended to the command verbatim - for flags the form does not cover.'
    },

    settings: {
      _tab: 'App defaults plus the server registry: one entry per TRex box (PCI NICs, cores, port identities). The Platform Config and CLI tabs read from here.',
      _sections: {},
      trexVersion: 'Default target version for new profiles and configs.',
      pcapDir: 'Where pcaps live on the box - used as a hint next to pcap path fields.',
      activeServer: 'Server preselected in the Platform Config tab.',
      name: 'Short name for this box, used in filenames and dropdowns.',
      mgmtHost: 'Management address (informational; shown in generated config headers).',
      trexDir: 'TRex install directory on the box - used in runbooks and launch scripts.',
      cores: 'Data-plane cores per dual-interface (becomes "c" in trex_cfg.yaml).',
      portLimit: 'How many ports TRex claims (port_limit).',
      bandwidth: 'NIC speed hint (port_bandwidth_gb): 1 for VMs, 10/40 for physical NICs.',
      interfaces: 'DPDK PCI addresses of the NICs TRex owns. Find them with ./dpdk_setup_ports.py -s on the box.',
      portMode: 'IP/gateway: TRex ARPs for the gateway (L3). MAC pair: static L2 addressing, typically cross-wired between paired ports.',
      platform: 'NUMA thread pinning: master and latency threads plus per-socket data-plane thread lists (dual_if).',
      memory: 'dp_flows sizes flow memory - raise it for millions of concurrent flows.',
      limitMemory: 'Cap TRex hugepage memory (MB).',
      prefix: 'Instance name prefix for running multiple TRex instances on one box.',
      zmqPub: 'Enable the ZMQ stats publisher.',
      telnetPort: 'Legacy telnet console port.'
    },

    emu: {
      _tab: 'Builds TRex-EMU client-emulation profiles: hundreds of emulated hosts that ARP, answer pings, lease DHCP addresses, join multicast groups and serve DNS/mDNS - the control-plane side of a test, driven by the separate trex-emu process.',
      _sections: {
        ns: 'EMU groups clients into namespaces keyed by vport (and optionally an 802.1Q tag). The --ns tunable creates N namespaces, incrementing the vport.',
        clients: 'The emulated hosts. Base MAC/IPv4/IPv6 values increment per client (mac[i], ipv4[i]...), exactly like the shipped emu/simple_*.py examples.',
        plugins: 'Per-protocol behaviours attached to every client (and matching namespace-level defaults). Enable only what the test needs.',
        dnsRecords: 'The zone database a DNS name-server client answers from: domain, record type and answer per entry.'
      },
      profileName: 'Name used for the generated .py file and when saving/loading this profile in the app.',
      nsCount: 'Number of namespaces to create (--ns tunable, one vport each). Most tests use 1.',
      vlan: 'Tag each namespace with an 802.1Q VLAN: tci increments with the vport so every namespace lands on its own VLAN.',
      vlanTci: 'VLAN tag of the first namespace; later namespaces increment from it.',
      clientCount: 'Clients per namespace (--clients tunable). EMU scales to many thousands.',
      clientMac: 'MAC of the first client; each further client increments it by one.',
      ipv4Enabled: 'Give clients static IPv4 addresses (incrementing). Untick when DHCPv4 should assign them.',
      ipv4: 'IPv4 of the first client; increments per client.',
      dg: 'Default gateway all clients use - normally the DUT-side router address.',
      ipv6Enabled: 'Give clients IPv6 addresses (incrementing).',
      ipv6: 'IPv6 of the first client; increments per client.',
      arp: 'Resolve and answer ARP - almost always on, or nothing can reach the clients.',
      arpTimer: 'Optional ARP refresh timer in seconds.',
      icmp: 'Answer ICMP echo - makes every emulated client pingable.',
      igmp: 'Join multicast groups via IGMP (namespace-level, needs the router MAC as dmac).',
      igmpDmac: 'Destination MAC for IGMP messages - the multicast router. Defaults to the first client MAC.',
      ipv6nd: 'IPv6 Neighbour Discovery: RS/NS/NA handling for the clients (the "ipv6" EMU plugin).',
      ipv6ndDmac: 'Destination MAC for IPv6 ND messages - the router. Defaults to the first client MAC.',
      dhcpv4: 'Lease IPv4 addresses over DHCP (discover/offer/request/ack). Clients then start at 0.0.0.0.',
      dhcpClassId: 'Optional vendor class-id option (60) sent in the discover/request messages.',
      dhcpv6: 'Lease IPv6 addresses over DHCPv6. Needs the IPv6 ND plugin.',
      dns: 'DNS plugin: clients either query a name server (resolver role) or answer as one (server role).',
      dnsMode: 'resolver client = sends queries to the name server IP; name server = answers from the records database.',
      dnsServerIp: 'IP (v4 or v6) of the DNS server the resolver clients query.',
      dnsDomain: 'Domain this record answers for, e.g. cisco.com.',
      dnsType: 'Record type: A (IPv4), AAAA (IPv6), TXT (free text) or PTR (reverse lookup).',
      dnsAnswer: 'The answer returned: an address for A/AAAA, text for TXT, a hostname for PTR.',
      mdns: 'Multicast DNS: clients announce hostnames and answer .local queries (needs IPv6 too, like emu/simple_mdns.py).',
      mdnsHosts: 'Hostname pattern each client announces; {} is replaced with the client number, e.g. client-{}.emu.',
      mdnsTtl: 'TTL in seconds for mDNS responses.',
      mdnsDomain: 'Optional mDNS domain name field.'
    },

    tpg: {
      _tab: 'Builds the Tagged Packet Group tags file: per-VLAN rx counters (packets, bytes, sequence errors) for Dot1Q and QinQ traffic, enabled from the console with tpg_enable.',
      _sections: {
        dot1q: 'Each VLAN in a range becomes one tag id: received packets carrying that 802.1Q tag are counted in their own bucket.',
        qinq: 'Each inner/outer VLAN pair becomes one tag id for 802.1ad QinQ traffic. QinQ entries take the first tag ids.',
        enable: 'Parameters of the tpg_enable console command that loads this file.'
      },
      name: 'Name used for the generated _tpg_tags.json file and when saving this config.',
      minVlan: 'First VLAN of the range (1-4094).',
      maxVlan: 'Last VLAN of the range, inclusive.',
      qinqInner: 'Inner (customer, 802.1Q) VLAN of the pair.',
      qinqOuter: 'Outer (service, 802.1ad) VLAN of the pair.',
      numTpgids: 'Upper bound of tpgid values the tx streams will use: every TPG stream needs flow_stats=STLTaggedPktGroup(tpgid=i) with i below this.',
      ports: 'Ports to enable TPG rx counting on (space separated, e.g. "0 1").'
    },

    bird: {
      _tab: 'Builds a BIRD routing daemon config for TRex\'s BIRD integration: BGP/OSPF/RIP sessions and generated static-route tables, advertised to the DUT through a veth node inside TRex.',
      _sections: {
        general: 'The BIRD router identity plus the veth node the runbook creates on a traffic port (this is the interface BIRD peers through).',
        bgp: 'One BGP protocol block per peering session with the DUT. Run several instances to peer on multiple interfaces.',
        igp: 'Interior gateway protocols on all BIRD interfaces, in the exact shipped bird/cfg shapes.',
        routes: 'Static route tables BIRD advertises: the builder expands "count" consecutive prefixes from the first one.'
      },
      name: 'Name used for the generated bird_<name>.conf and when saving this config.',
      routerId: 'BIRD router id in dotted-quad form. Any unique IPv4-shaped value works.',
      nodePort: 'TRex port the bird veth node attaches to.',
      nodeMac: 'MAC of the veth node inside the BIRD namespace.',
      nodeIp: 'IPv4 of the bird node - BGP "local" addresses must live on this interface.',
      nodeSubnet: 'Prefix length of the node address.',
      nodeIpv6: 'Optionally give the node an IPv6 address for IPv6 peering.',
      bgpName: 'BIRD protocol instance name - must be unique in the config.',
      bgpAf: 'Address family of the session channel (ipv4 or ipv6 import/export).',
      bgpLocal: 'Local session address (an address of the bird node) - "local <ip> as <asn>".',
      bgpNeighbor: 'Peer address on the DUT - "neighbor <ip> as <asn>".',
      bgpAs: 'Autonomous system number (same on both = iBGP, different = eBGP).',
      ospf: 'OSPF on all BIRD interfaces as broadcast type, importing and exporting everything.',
      ospfArea: 'OSPF area number (0 = backbone).',
      rip: 'RIP in multicast mode on all BIRD interfaces.',
      routeAf: 'IPv4 blocks can generate many consecutive prefixes; IPv6 blocks emit a single route.',
      routePrefix: 'First destination prefix, e.g. 42.42.42.0.',
      routeLen: 'Prefix length; consecutive routes step by the prefix size so they never overlap.',
      routeCount: 'How many consecutive prefixes to emit. Above 5000 use the runbook\'s server-side generation instead.',
      routeNextHop: 'Next hop for every generated route - best practice is the bird node\'s own address.'
    }
  };
})(typeof window !== 'undefined' ? window : globalThis);
